version: '3'


services:

  Test:
    image: 'DCPTester_ubuntu'
    user: root
    working_dir: /var/build
    volumes:
      - ./data/:/var/share:z
    build: ./docker
    command: >
        /bin/bash -c "ls /var/build/"
